server:
  port: 3000
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: dokky
  jpa:
    database: h2
    show-sql: true
    hibernate:
      # create : ?? ??? ?? ? ?? ??
      # create-drop : create? ??? ????? ??? ?? drop

      # update : ??? ??? ?? (???? ??x)
      # validate : ???? ???? ?? ?? ????? ?? -> ?? ?? ?? ?? ??
      # none : ???? ??
      # ????? ?? create, create-drop, update ???? ??
      # ?? ?? ?? create or update
      # ??? ?? update (??? ??x) or validate
      # ????, ?? validate or none
      ddl-auto: update
      open-in-view: true

#management:
#  endpoints:
#    web:
#      base-path: /api


