spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/study/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

infra:
  external:
    cherry:
      host: dev-api.cherryforce.kr
      category-url: https://${infra.external.cherry.host}/v1/categories
      product-url: https://${infra.external.cherry.host}/v1/products
